src/whathappened/web/character/coc7e/forms.py
"""Forms for CoC7e."""

from wtforms import SelectField

from whathappened.core.sheets.mechanics.coc7e import GameTypes

from ..forms import CreateForm as BaseCreateForm


class CreateForm(BaseCreateForm):
    """CoC7e create form."""

    gametype = SelectField(
        "Type",
        choices=[(gt, gt) for gt in GameTypes],
    )

src/whathappened/web/character/forms.py
"""Character forms."""

import json
import logging
from typing import Optional
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, HiddenField
from wtforms import ValidationError, SubmitField
from wtforms import Field
from wtforms.validators import DataRequired

from whathappened.web.forms.fields import JsonField

logger = logging.getLogger(__name__)


class JsonString(object):
    """Validate string as JSON."""

    def __init__(self, message: Optional[str] = None):
        if not message:
            message = "Field must be a valid JSON string"
        self.message = message

    def __call__(self, _: FlaskForm, field: Field):
        try:
            _ = json.loads(field.data)
        except Exception as exc:
            logger.error("Could not verify JSON data", exc_info=True)
            raise ValidationError(self.message) from exc


class ImportForm(FlaskForm):
    """Character importing form."""

    title = StringField("Title", validators=[DataRequired()])
    body = JsonField("Body", validators=[DataRequired()])
    conversion = BooleanField("Convert")
    migration = BooleanField("Migrate")
    submit = SubmitField("Import")


class EditForm(ImportForm):
    """Edit charcter data form."""

    archived = BooleanField("Archived")


class CreateForm(FlaskForm):
    """Create new character form."""

    title = StringField("Title", validators=[DataRequired()])
    system = HiddenField("System", validators=[DataRequired()])
    submit = SubmitField("Create")


class SkillForm(FlaskForm):
    """Edit skill form."""

    name = StringField("Name", validators=[DataRequired()])
    # value = IntegerField('Value', validators=[DataRequired()])
    submit = SubmitField("Add")


class SubskillForm(FlaskForm):
    """Edit subskill form."""

    name = StringField("Name", validators=[DataRequired()])
    parent = HiddenField("Parent", validators=[DataRequired()])
    submit = SubmitField("Add")


class DeleteForm(FlaskForm):
    """Delete character form."""

    character_id = HiddenField("CharacterId", validators=[DataRequired()])
    submit = SubmitField("Delete")

src/whathappened/character/routes.py
import copy
import logging
from typing import Optional

from flask import render_template, request
from flask import redirect, url_for, jsonify
from werkzeug.exceptions import abort

from whathappened.web.auth.utils import login_required, current_user
from whathappened.web.content.forms import ChooseFolderForm
from whathappened.core.database import session
from whathappened.core.database.pagination import paginate
from whathappened.core.database.models import Invite, LogEntry
from whathappened.core.sheets.mechanics import core
from whathappened.core.sheets.mechanics.core import GameSystems
from whathappened.core.sheets.schema.base import CURRENT_SCHEMA_VERSION
from whathappened.core.sheets.schema.build import flatten_schema, get_schema, sub_schema
from whathappened.core.sheets.schema.utils import migrate

from .blueprints import bp, api
from ..core.character.models import Character
from .forms import EditForm, CreateForm, ImportForm
from .forms import DeleteForm

# Imports for registering games.
from . import coc7e  # noqa
from whathappened.core.sheets.mechanics.coc7e.convert import convert_from_dholes
from . import tftl  # noqa


logger = logging.getLogger(__name__)


def get_character(id: int, check_author: bool = True) -> Character:
    character = session.get(Character, id)

    if character is None:
        abort(404, "Character id {0} doesn't exist.".format(id))

    if current_user.has_role("admin"):  # pyright: ignore[reportGeneralTypeIssues]
        return character

    if character.viewable_by(current_user.profile):
        return character

    if check_author and character.user_id != current_user.profile.id:  # pyright: ignore[reportGeneralTypeIssues]
        abort(403)

    return character


@bp.route("/")
def index():
    return redirect("/")


@bp.route("/create/<string:chartype>/", methods=("GET", "POST"))
def create(chartype: str):
    character_module = globals()[chartype] if chartype in globals() else core

    form = getattr(character_module, "CreateForm", CreateForm)()
    template = getattr(
        character_module, "CREATE_TEMPLATE", "character/create.html.jinja"
    )

    if form.validate_on_submit():
        logger.debug(f"Creating new character specified by {form.data}")
        char_data = character_module.new_character(**form.data)
        assert isinstance(char_data, dict)
        c = Character(
            title=form.title.data, body=char_data, user_id=current_user.profile.id
        )  # pyright: ignore[reportGeneralTypeIssues]
        session.add(c)
        session.commit()
        return redirect(url_for("character.view", id=c.id))

    form.system.data = chartype
    return render_template(template, form=form, type=type)


@bp.route("/create/", methods=("GET",))
@login_required
def system_select(chartype=None):
    return render_template("character/system_select.html.jinja", systems=GameSystems)


@bp.route("/import/<string:type>", methods=("GET", "POST"))
@bp.route("/import/<int:id>", methods=("GET", "POST"))
@bp.route("/import/<uuid:code>", methods=("GET", "POST"))
@bp.route("/import", methods=("GET", "POST"))
@login_required
def import_character(
    type: Optional[str] = None, id: Optional[int] = None, code: Optional[str] = None
):
    logger.debug(f"{type}, {code}, {id}")
    character = None
    if id:
        character = get_character(id, check_author=True)
    elif code is not None:
        invite = session.get(Invite, code)
        if invite is None or invite.table != Character.__tablename__:
            return "Invalid code"
        character = session.get(Character, invite.object_id)

    form = ImportForm(obj=character)
    if form.validate_on_submit():
        c = Character(
            title=form.title.data, body=form.body.data, user_id=current_user.profile.id
        )  # pyright: ignore[reportGeneralTypeIssues]
        session.add(c)
        session.commit()
        return redirect(url_for("character.view", id=c.id))
    return render_template("character/import.html.jinja", form=form, type=None)


@bp.route("/<int:id>/update", methods=("POST",))
@login_required
def update(id: int):
    character = get_character(id, check_author=True)

    if request.method == "POST":
        update = request.get_json()
        assert update is not None
        for setting in update:
            name = character.set_attribute(setting)
            field = setting["field"]
            subfield = setting.get("subfield", "")
            value = setting["value"]
            type = setting.get("type", "value")
            if type == "portrait" and value is not None:
                value = "[image]"

            log_subfield = ""
            if subfield is not None and subfield != "None":
                log_subfield = " " + subfield
            if name is not None:
                log_message = f"set {type} on {field}{log_subfield} ({name}): {value}"
            else:
                log_message = f"set {type} on {field}{log_subfield}: {value}"

            logentry = LogEntry(character, log_message, user_id=current_user.id)  # pyright: ignore[reportGeneralTypeIssues]
            session.add(logentry)

        character.store_data()
        session.commit()

    return "OK"


def render_character(
    character: Character, editable: bool = False, code: Optional[str] = None
):
    if editable:
        if (not character.archived) and character.validate():
            logger.debug("Character sheet invalid, trying migration.")
            backup_data = copy.deepcopy(character.body)
            data = character.body
            try:
                prev_version = character.schema_version
                character.body = migrate(data, CURRENT_SCHEMA_VERSION)
                if not character.validate():
                    logentry = LogEntry(
                        character,
                        "Character was automatically migrated.",
                        user_id=current_user.id,
                    )  # pyright: ignore[reportGeneralTypeIssues]
                    session.add(logentry)

                    backup_character = Character(
                        title=f"{character.title}-{prev_version}-backup",
                        body=backup_data,
                        user_id=character.user_id,
                        archived=True,
                    )
                    session.add(backup_character)
                    session.commit()
            except KeyError:
                ...

        if character.system is None or character.validate():
            return redirect(url_for("character.edit", id=character.id))

    character_module = (
        globals()[character.system] if character.system in globals() else core
    )

    system_view = getattr(character_module, "view", None)

    if system_view is not None:
        return system_view(character.id, character, editable)

    system_template = getattr(character_module, "CHARACTER_SHEET_TEMPLATE", None)

    if system_template:
        return render_template(
            character_module.CHARACTER_SHEET_TEMPLATE,
            character=character,
            editable=editable,
            code=code,
        )

    return render_general_view(
        character.system, character=character, editable=editable, code=code
    )


@bp.route("/<uuid:code>", methods=("GET",))
def shared(code: str):
    invite = session.get(Invite, code)
    if invite is None or invite.table != Character.__tablename__:
        return "Invalid code"

    character = session.get(Character, invite.object_id)

    return render_character(character, editable=False, code=code)


@bp.route("/<int:id>/", methods=("GET", "POST"))
@login_required
def view(id: int):
    character = get_character(id, check_author=True)

    editable = current_user.is_authenticated and character.editable_by(
        current_user.profile
    )

    return render_character(character, editable=editable)


def html_data_type(t: str) -> str:
    if t == "integer":
        return "number"
    return t


def render_general_view(
    system: str, character: Character, editable: bool, code: Optional[str] = None
):
    logger.debug("Getting schema")
    schema = get_schema(system)
    schema = flatten_schema(schema)
    return render_template(
        "character/general_character.html.jinja",
        schema=schema,
        character=character,
        editable=editable,
        html_data_type=html_data_type,
        get_ref=sub_schema,
        code=code,
    )


@bp.route("/<int:id>/tokens/", methods=("GET", "POST"))
@login_required
def tokens(id: int):
    character = get_character(id, check_author=False)

    return render_template("character/tokens.html.jinja", picture=character.portrait)


@api.route("/<int:id>/", methods=("GET",))
def get(id: int):
    """API call to get all character data."""
    data = get_character(id, check_author=True)
    return jsonify(data.to_dict())


@bp.route(
    "/<int:id>/delete",
    methods=(
        "GET",
        "POST",
    ),
)
@api.route(
    "/<int:id>/delete",
    methods=(
        "GET",
        "POST",
    ),
)
@login_required
def delete(id: int):
    """Delete a character."""
    character = get_character(id, check_author=True)

    if current_user.profile.id != character.user_id:  # pyright: ignore[reportGeneralTypeIssues]
        abort(404)

    form = DeleteForm()
    if form.validate_on_submit():
        session.delete(character)
        session.commit()
        return redirect(url_for("character.index"))

    form.character_id.data = character.id

    return render_template(
        "character/delete_character.html.jinja", form=form, character=character
    )


@api.route("/<int:id>/share", methods=("GET",))
@login_required
def share(id: int):
    """Share a character."""
    character = get_character(id, check_author=True)
    logger.debug("Finding previous invite")
    invite = Invite.query_for(character).first()
    logger.debug(f"Invites found {invite}")
    if not invite:

src/whathappened/core/character/coc7e/__init__.py
"""Special cases for Call of Cthulhu."""

import logging
from whathappened.core.sheets.mechanics.coc7e import new_character

logger = logging.getLogger(__name__)


__all__ = ["new_character"]

src/whathappened/web/character/__init__.py
"""Module for the interaction with character sheets in What Happened?"""

import math
from pelican.plugins.webassets.vendor.webassets.env import Environment

from . import routes  # noqa: E402, F401 isort:skip
from .blueprints import bp


@bp.app_template_filter("datetimeformat")
def datetimeformat(value, formatstring: str = "%Y-%m-%d %H:%M:%S"):
    """Jinja filter for formatting datetimes."""
    return value.strftime(formatstring)


@bp.app_template_filter("valuetostring")
def valuetostring(value):
    if isinstance(value, dict):
        return ", ".join(f"{k}: {v}" for k, v in value.items())
    return value


@bp.app_template_filter("half")
def half(value):
    if not value:
        return 0
    if isinstance(value, str):
        try:
            value = int(value, 10)
        except ValueError:
            return 0
    return math.floor(value / 2)


@bp.app_template_filter("fifth")
def fifth(value):
    if not value:
        return 0
    if isinstance(value, str):
        try:
            value = int(value, 10)
        except ValueError:
            return 0
    return math.floor(value / 5)


def register_assets(assets: Environment):
    """Register style assets."""
    assets.register(
        "scss_character",
        "scss/character/character.scss",
        filters="pyscss",
        output="css/character.css",
    )
    assets.register(
        "scss_character_general",
        "scss/character/character_general.scss",
        filters="pyscss",
        output="css/character_general.css",
    )
    assets.register(
        "scss_character_coc7e",
        "scss/character/character_coc7e.scss",
        filters="pyscss",
        output="css/character_coc7e.css",
    )

    assets.register(
        "scss_character_tftl",
        "scss/character/character_tftl.scss",
        filters="pyscss",
        output="css/character_tftl.css",
    )

src/whathappened/web/character/blueprints.py
"""Character blueprints."""

from flask import Blueprint

bp = Blueprint(
    "character", __name__, template_folder="templates", static_folder="static"
)
api = Blueprint("characterapi", __name__, template_folder="templates")

src/whathappened/web/character/coc7e/__init__.py
"""Special cases for Call of Cthulhu."""

import logging
from whathappened.core.sheets.mechanics.coc7e import new_character
from .forms import CreateForm
from .routes import view

logger = logging.getLogger(__name__)

CREATE_TEMPLATE = "character/coc7e/create.html.jinja"

__all__ = ["CreateForm", "view", "new_character"]

src/whathappened/web/character/coc7e/routes.py
"""Special routes for CoC7e."""

from flask import redirect, render_template, url_for, flash

from whathappened.core.database.models import LogEntry, Invite
from whathappened.core.database import session
from whathappened.web.auth.utils import current_user

from ..forms import SkillForm, SubskillForm


def view(character_id, character, editable):
    """Custom view for CoC7e."""
    subskillform = SubskillForm(prefix="subskillform")
    if editable and subskillform.data and subskillform.validate_on_submit():
        character.mechanics.add_subskill(
            subskillform.name.data, subskillform.parent.data
        )
        logentry = LogEntry(
            character,
            f"add subskill {subskillform.name.data} "
            + f"under {subskillform.parent.data}",
            user_id=current_user.id,
        )
        session.add(logentry)

        character.store_data()
        session.commit()
        return redirect(url_for("character.view", character_id=character_id))

    skillform = SkillForm(prefix="skillform")
    if editable and skillform.data and skillform.validate_on_submit():
        skills = character.skills()
        for skill in skills:
            if skillform.name.data == skill["name"]:
                flash("Skill already exists")
                return redirect(url_for("character.view", character_id=character_id))

        character.add_skill(skillform.name.data)
        character.store_data()
        logentry = LogEntry(
            character, f"add skill {subskillform.name.data}", user_id=current_user.id
        )
        session.add(logentry)

        session.commit()
        return redirect(url_for("character.view", character_id=character_id))

    shared = Invite.query_for(character).count()

    return render_template(
        "character/coc7e/sheet.html.jinja",
        shared=shared,
        character=character,
        editable=editable,
        skillform=skillform,
        subskillform=subskillform,
    )

src/whathappened/web/character/tftl/__init__.py
"""Tftl web specific things."""

from whathappened.core.sheets.mechanics.core import new_character

CREATE_TEMPLATE = "character/tftl/create.html.jinja"
CHARACTER_SHEET_TEMPLATE = "character/tftl/sheet.html.jinja"

__all__ = ["new_character"]

src/whathappened/templates/character/api_share.html.jinja
<p>
    Sharable link: <a href="{{ url }}">{{ url }}</a> [<a href="{{ url_for('main.invite_delete', invite_id=code) }}">Delete</a>]
</p>

src/whathappened/templates/character/create.html.jinja
{% extends 'base.html.jinja' %}

{% block header %}
  <h2>{% block title %}New Character{% endblock %}</h2>
{% endblock %}

{% block content %}
  <form action="" method="post">
    {{ form.hidden_tag() }}
        <p>
          {{ form.title.label }}<br>
          {{ form.title(size=32) }}<br>
          {% for error in form.title.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>{{ form.submit() }}</p>
  </form>
{% endblock %}

src/whathappened/templates/character/delete_character.html.jinja
{% extends 'base.html.jinja' %}

{% block head %}
    {{ super() }}

{% endblock %}

{% block header %}
    <h2>{% block title %}Delete "{{ character.title }} {{ character.name }}" ? {% endblock %}</h2>
{% endblock %}

{% block content %}
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ form.submit() }}
    </form>
{% endblock %}

src/whathappened/templates/character/edit.html.jinja
{% extends 'base.html.jinja' %}

{% block header %}
  <h2>{% block title %}{{ title or "Edit character"}}{% endblock %}</h2>
{% endblock %}

{% block content %}
  <div>
    Remember to backup your character before doing anything you are not really sure about!
  </div>
  <form action="" method="post">
    {{ form.hidden_tag() }}
        <p>
          {{ form.title.label }}<br>
          {{ form.title(size=32) }}<br>
          {% for error in form.title.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p class="editjson">
          {{ form.body.label }}<br>
          {{ form.body() }}<br>
          {% for error in form.body.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>        
      <p>
      {{ form.migration() }} Try data migration.
      </p>
      <p>
      {{ form.conversion() }} Try to convert from Dholes.
      </p>
      <p>
      {{ form.archived() }} Character is archived.
      </p>
      <p>{{ form.submit() }}</p>  
      <p>
        If you check the box, upon save, the system will try to convert the data from formats used by other generators.
        Use with caution. Backup the data first.
        </p>
  </form>
  {% if validation_errors %}
    <h3>Validation errors in character sheet</h3>
    {% for error in validation_errors %}
      {{ error.path }}: {{ error.message }}<br />
    {% endfor %}
  {% endif %}

    <a href="{{ url_for('character.delete', character_id=character.id) }}">Delete</a>
{% endblock %}

src/whathappened/templates/character/eventlog.html.jinja
{% extends 'base.html.jinja' %}

{% block header %}
  <h2>{% block title %}Event log for <a href="{{ url_for('character.view', character_id=character.id)}}">{{ character.title}}</a>{% endblock %}</h2>
{% endblock %}

{% block content %}
<table>
{% for entry in entries %}
    <tr>
        <td>{{ entry.created_date|datetimeformat }}</td>
        <td>{{ entry.user.username}}</td>
        <td>{{ entry.entry }}</td>
    </tr>
{% endfor %}
</table>
{% if prev_url or next_url %}
{% if prev_url %}<a href="{{prev_url}}">Prev</a>{% else %}Prev{% endif %}
{% if next_url %}<a href="{{next_url}}">Next</a>{% else %}Next{% endif %}
{% endif %}
{% endblock %}

src/whathappened/templates/character/index.html.jinja
{% extends 'base.html.jinja' %}

{% block header %}
  <h2>{% block title %}Character{% endblock %}</h2>
  {% if not current_user.is_anonymous %}
    <a class="action" href="{{ url_for('character.create', chartype='coc7e') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for character in characters %}
    <article class="character">
      <header>
        <div>
        <a class="action" href="{{ url_for('character.view', character_id=character['id']) }}">
          <h3>{{ character['title'] }}</h3>
          </a>
          <div class="about">by {{ character['username'] }} on {{ character['created'].strftime('%Y-%m-%d') }}</div>
        </div>
      </header>
      <div class="character body summary">
      <div style="display: inline-block; vertical-align: top;">
        {{ character['data']['Investigator']['PersonalDetails']['Name'] }}<br />
        {{ character['data']['Investigator']['PersonalDetails']['Occupation'] }}<br />
        {{ character['data']['Investigator']['PersonalDetails']['Gender'] }}<br />
        {{ character['data']['Investigator']['PersonalDetails']['Age'] }}<br />
        {{ character['data']['Investigator']['PersonalDetails']['Birthplace'] }}<br />
        {{ character['data']['Investigator']['PersonalDetails']['Residence'] }}<br />
    </div>
    <div style="display: inline-block; vertical-align: top;">
        <img src="data:image/jpg;base64, {{ character['data']['Investigator']['PersonalDetails']['Portrait'] }}" />
        </div>
      </div>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

src/whathappened/templates/character/move_to_folder.html.jinja
{% extends 'base.html.jinja' %}

{% block content %}
<section id="move_to_folder">
    <form action="{{ url_for('character.folder', character_id=character.id) }}" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.folder_id }}
            {% for error in form.folder_id.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}

            {{ form.choose()}}
        </p>
    </form>
</section>

{% endblock %}

src/whathappened/templates/character/sheet.html.jinja
{% extends 'base.html.jinja' %}

{% block head %}
{{ super() }}

{% assets "scss_character" %}
<link rel=stylesheet type=text/css href="{{ ASSET_URL }}">
{% endassets %}

<script src="{{ 'sheet.js' | webpack}}"></script>

{% endblock %}

{% block header %}
<h2>{% block title %}{{ character.title }}{% endblock %}</h2>
{% endblock %}

{% block menu %}
{% if current_user.is_authenticated %}
<a href="{{ url_for('character.export', character_id=character['id']) }}">Export</a>
| <a
    href="{{ url_for('character.import_character', character_id=character.id) if editable else url_for('character.import_character', code=code) }}">Copy</a>
{%- if editable %}
| <a href="{{ url_for('character.edit', character_id=character.id) }}">Edit</a>
| <a href="{{ url_for('character.delete', character_id=character.id) }}">Delete</a>
| <a href="#" id="sharebtn" data-id="{{ character.id }}">{% if not shared %}Share{% else %}Share link{% endif %}</a>
| <a href="{{ url_for('character.eventlog', character_id=character.id) }}">Event log</a>
| <a href="{{ url_for ('character.folder', character_id=character.id) }}">Choose folder</a>
{%- endif %}
| <a href="{{ url_for('character.tokens', character_id=character.id) }}">Tokens</a>
{% endif %}
{% endblock %}

{%- macro editable_field(field, default='', type='string', minimum=None, maximum=None, filter="", constant=False) %}
<span {%- if editable and not constant %} class="editable" {%- endif %} data-field="{{ field }}" data-type="{{ type }}"
    {%- if minimum %}data-min="{{minimum}}" {%- endif %} {%- if maximum %}data-max="{{maximum}}"
    {%- endif %} title="{{type|capitalize}}{%- if minimum %} Minimum: {{minimum}}{%- endif %}{%- if maximum %} Maximum: {{maximum}}{%- endif%}">{{
    character.mechanics.attribute(field)|uberfilter(filter) }}</span>
{%- endmacro %}

{%- macro editable_choice(field, default='', type='string', choices=[], constant=False, values={}) -%}
 <span {%- if editable and not constant %} class="editable" {%- endif %} data-field="{{ field }}" data-type="{{ type }}"
    data-choices='{{ choices|tojson }}' data-values='{{ (values or {} )|tojson }}' data-value="{{ character.mechanics.attribute(field) }}">{{ values.get(character.mechanics.attribute(field), character.mechanics.attribute(field)) }}</span>
{%- endmacro -%}


{%- macro editable_skill(field, subfield=None, default='', type='string') %}
<span {%- if editable %} class="editable" {%- endif %} data-field="{{ field }}" data-subfield="{{subfield}}"
    data-type="{{ type }}" data-category="skill">{{ character.skill(field, subfield)['value'] or '_' }}</span>
<span class="half">{{ character.skill(field, subfield)['value']|half }}</span>
<span class="fifth">{{ character.skill(field, subfield)['value']|fifth }}</span>
{%- endmacro %}

{%- macro editable_stat(field, default='', type='string') %}
<span {%- if editable %} class="editable" {%- endif %} data-field="{{ field }}" data-type="{{ type }}">{{
    character.mechanics.attribute(field) }}</span>
<span class="half">{{ character.mechanics.attribute(field)|half }}</span>
<span class="fifth">{{ character.mechanics.attribute(field)|fifth }}</span>

{%- endmacro %}

{%- macro editable_area(field, default='') %}
<pre {%- if editable %} class="editable freetext" {%- endif %} data-field="{{field}}"
    data-type="area">{{ character.mechanics.attribute(field) or default }}</pre>
{%- endmacro %}


{%- macro editable_binary(field, default=False) %}
{%- if editable %}<input type="checkbox" data-field="{{field}}" data-type="binary" {%- if
    character.mechanics.attribute(field) %}checked{%- endif %} />{%- else %}
{%- if character.mechanics.attribute(field)%}*{%- else %}&nbsp;&nbsp;{%- endif %}
{%- endif %}
{%- endmacro %}

{%- macro skill_checkmark(field, subfield=None) %}
{%- if editable %}<input type="checkbox" data-field="{{field}}" data-subfield="{{subfield}}" data-type="skillcheck" {%-
    if character.skill(field, subfield)['checked'] %}checked{%- endif %} />{%- else %}
{%- if character.skill(field, subfield)['checked'] %}*{%- else %}&nbsp;&nbsp;{%- endif %}
{%- endif %}
{%- endmacro %}

{%- macro editable_weapon(key, weapon) %}
{{ key }}
{%- endmacro %}

{%- macro editable_lines(key, default) %}
{% for item in character.mechanics.attribute(key) or default %}
{{ item }}
{% endfor %}
{%- endmacro %}


{%- macro render_progress(path, value, points=10) %}
<span {%- if editable %} class="editable_check_progress" {%- endif %} data-field="{{path}}" data-value="{{ value }}">
    <span data-type="number" id="{{path}}-value">{{ value }}</span>
    {% for v in range(points) %}
    <input type="checkbox" {{ "checked" if v < value }} autocomplete="off"
        data-value="{{ v + 1}}" />
    {% endfor %}
</span>
{%- endmacro %}

{% macro extra_info(character, campaign, editable=False) %}
    {% if editable and character.campaign_associations %}
    In campaign(s): 
    <ul>
    {% for association in character.campaign_associations %}
    <li><a href="{{url_for('campaign.view', campaign_id=association.campaign.id)}}">{{
        association.campaign.title
        }}</a>{%- if association.editable_by_gm %}, editable by GM
        {%- endif %}{%- if association.share_with_players %}, viewable by players {%- endif %}{%- if association.group_sheet %}, editable by group {%- endif %}</li>
    {% endfor %}
    </ul>
    {% endif %}
{% endmacro %}

{% block footer %} - {{ character.data.meta.gamename }} ({{ character.data.system }}@{{ character.data.version }}) {% endblock %}

src/whathappened/templates/character/system_select.html.jinja
{% extends 'base.html.jinja' %}

{% block header %}
  <h2>{% block title %}New Character{% endblock %}</h2>
{% endblock %}

{% block content %}
  {% for system, name in systems %}
    <a href="{{ system }}/">{{ name }}</a><br />
  {% endfor %}
{% endblock %}

src/whathappened/templates/character/update.html.jinja
{% extends 'base.html.jinja' %}

{% block header %}
  <h2>{% block title %}Edit "{{ character['title'] }}"{% endblock %}</h2>
{% endblock %}

{% block content %}
  <form method="post">
    <label for="title">Title</label>
    <input name="title" id="title"
      value="{{ request.form['title'] or character['title'] }}" required>
    <label for="body">Body</label>
    <textarea name="body" id="body">{{ request.form['body'] or character['body'] }}</textarea>
    <input type="submit" value="Save">
  </form>
  <hr>
  <form action="{{ url_for('character.delete', character_id=character['id']) }}" method="post">
    <input class="danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
  </form>
{% endblock %}