src/whathappened/campaign/forms.py
from typing import List, Tuple
from flask_wtf import FlaskForm
from wtforms import StringField, HiddenField, SelectField, BooleanField
from markupsafe import Markup
from wtforms import SubmitField
from wtforms import widgets
from wtforms import IntegerField, SelectMultipleField
from wtforms.validators import DataRequired, Email
from wtforms.widgets.core import HiddenInput, TextArea

from whathappened.web.forms.fields import QuerySelectField, QuerySelectMultipleField
from whathappened.auth.utils import current_user

from ..core.campaign.models import HandoutStatus


class CreateForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    characters_enabled = BooleanField("Use Characters")
    npcs_enabled = BooleanField("Use NPCs")
    handouts_enabled = BooleanField("Use handouts")
    messages_enabled = BooleanField("Use messages")
    submit = SubmitField("Create")


class EditForm(CreateForm):
    id = IntegerField(widget=HiddenInput())
    description = StringField("Description", widget=TextArea())
    submit = SubmitField("Save")


class DeleteForm(FlaskForm):
    id = IntegerField(widget=HiddenInput())
    confirm = StringField("Confirm", validators=[DataRequired()])
    submit = SubmitField("Delete")


class InvitePlayerForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired(), Email()])
    submit = SubmitField("Invite")


def available_characters():
    return current_user.profile.characters  # pyright: ignore[reportGeneralTypeIssues]


class AddCharacterForm(FlaskForm):
    character = QuerySelectField(
        query_factory=available_characters, get_label=lambda x: x.title
    )
    submit = SubmitField("Add character")


class AddNPCForm(AddCharacterForm):
    visible = BooleanField("Visible", default=False)


class CampaignAssociationForm(FlaskForm):
    """Edit settings for a character-campaign association."""

    campaign_id = IntegerField(widget=HiddenInput())
    character_id = IntegerField(widget=HiddenInput())
    editable_by_gm = BooleanField("Editable by GM", default=False)
    share_with_players = BooleanField("Share with players", default=False)
    group_sheet = BooleanField("Group sheet", default=False)
    submit = SubmitField("Update settings")


class RemoveCharacterForm(FlaskForm):
    id = IntegerField(widget=HiddenInput())
    character = IntegerField(widget=HiddenInput())
    submit = SubmitField("Remove character")


class RemovePlayerForm(FlaskForm):
    id = IntegerField(widget=HiddenInput())
    player = IntegerField(widget=HiddenInput())
    submit = SubmitField("Remove player")


class JoinCampaignForm(FlaskForm):
    invite_code = HiddenField("Invite", validators=[DataRequired()])
    submit = SubmitField("Join campaign")


class EnumField(SelectField):
    def process_data(self, value):
        if value is not None:
            value = value.name
        super(EnumField, self).process_data(value)


class PlayerListField(QuerySelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()


class HandoutGroupForm(FlaskForm):
    campaign_id = IntegerField(widget=HiddenInput(), validators=[DataRequired()])
    name = StringField("Name", validators=[DataRequired()])
    submit = SubmitField("Add group")


class HandoutForm(FlaskForm):
    campaign_id = IntegerField(widget=HiddenInput(), validators=[DataRequired()])
    title = StringField("Title", validators=[DataRequired()])
    content = StringField("Content", widget=TextArea())
    status = EnumField(
        "Status",
        choices=[(e.name, e.value) for e in HandoutStatus],
        default=HandoutStatus.draft,
    )

    group_id = SelectField(
        "Group",
        choices=[
            ("", "(none)"),
        ],
        default="",
        validate_choice=False,
    )

    submit = SubmitField("Save handout")


class DeleteHandoutForm(FlaskForm):
    campaign_id = IntegerField(widget=HiddenInput(), validators=[DataRequired()])
    id = IntegerField(widget=HiddenInput(), validators=[DataRequired()])
    submit = SubmitField("Delete handout")


class TableRowWidget(object):
    def __init__(self, with_tr_tag: bool = True):
        self.with_tr_tag = with_tr_tag

    def __call__(self, field, **kwargs):
        html = []
        if self.with_tr_tag:
            kwargs.setdefault("id", field.id)
            html.append("<tr %s>" % widgets.html_params(**kwargs))

        hidden = ""
        for subfield in field:
            if subfield.type in ("HiddenField", "CSRFTokenField"):
                hidden += str(subfield)
            else:
                html.append("<td>%s%s</td>" % (hidden, str(subfield)))
                hidden = ""
        if self.with_tr_tag:
            html.append("</tr>")
        if hidden:
            html.append(hidden)
        return Markup("".join(html))


class PlayerField(SelectMultipleField):
    widget = TableRowWidget(with_tr_tag=False)
    option_widget = widgets.CheckboxInput()


class RevealHandout(FlaskForm):
    campaign_id = IntegerField(widget=HiddenInput(), validators=[DataRequired()])
    id = IntegerField(widget=HiddenInput(), validators=[DataRequired()])
    players = QuerySelectMultipleField("Show to", get_label=lambda x: x.user.username)


class NPCTransferForm(FlaskForm):
    npc_id = IntegerField(widget=HiddenInput(), validators=[DataRequired()])
    player = SelectField(validate_choice=False)
    submit = SubmitField("Transfer NPC")


class MessagePlayerForm(FlaskForm):
    campaign_id = IntegerField(widget=HiddenInput(), validators=[DataRequired()])
    from_id = IntegerField(widget=HiddenInput(), validators=[DataRequired()])
    message = StringField()
    submit = SubmitField("Send...")

    to_id = SelectField(
        "To",
        choices=[
            ("", "All"),
        ],
        validate_choice=False,
    )

    def __init__(
        self,
        hide_to_id: bool = False,
        players: List[Tuple[int, str]] = [],
        *args,
        **kwargs,
    ):
        super().__init__(*args, **kwargs)
        if hide_to_id:
            self.to_id.widget = HiddenInput()  # type: ignore  # Not an error

        player_choices: List[Tuple[int | str, str]] = [("", "All")]
        player_choices += players
        self.to_id.choices = player_choices

        assert self.to_id.choices is not None

src/whathappened/campaign/__init__.py
from webassets.env import Environment


from . import routes  # noqa: F401,E402 isort:skip
from . import views  # noqa: F401, E402 isort:skip
from . import api  # noqa: F401, E402 isort:skip
from ..core.campaign.models import Campaign  # noqa: F401, E402 isort:skip


def register_assets(assets: Environment):
    assets.register(
        "scss_campaign",
        "scss/campaign/campaign.scss",
        filters="pyscss",
        output="css/campaign.css",
    )

    assets.register(
        "scss_handout",
        "scss/campaign/handout.scss",
        filters="pyscss",
        output="css/handout.css",
    )

src/whathappened/campaign/routes.py
import logging
from typing import Optional

from flask import render_template, redirect, url_for, flash, request
from sqlalchemy import and_, or_, desc
from werkzeug.exceptions import abort

from whathappened.main.forms import CreateInviteForm
from whathappened.core.auth.models import User
from whathappened.core.character.models import Character
from whathappened.core.database.models import UserProfile, Invite
from whathappened.core.database import session
from whathappened.content.forms import ChooseFolderForm
from whathappened.auth.utils import login_required, current_user

from .blueprints import bp
from ..core.campaign.models import Campaign, CampaignCharacter
from .forms import (
    CreateForm,
    DeleteForm,
    InvitePlayerForm,
    AddCharacterForm,
    AddNPCForm,
)
from .forms import (
    JoinCampaignForm,
    EditForm,
    RemoveCharacterForm,
    CampaignAssociationForm,
)
from .forms import RemovePlayerForm, NPCTransferForm, MessagePlayerForm
from ..core.campaign.models import HandoutStatus, NPC, Message

from . import api  # noqa

logger = logging.getLogger(__name__)


@bp.route("/<code>", methods=("GET", "POST"))
@login_required
def join(code: str):
    inv = session.get(Invite, code)

    if inv is None or inv.table != Campaign.__tablename__:
        return "Invalid code"

    joinform = JoinCampaignForm()
    if joinform.validate_on_submit():
        campaign = session.get(Campaign, inv.object_id)
        assert campaign
        player = current_user.profile
        if player not in campaign.players:
            campaign.players.append(player)
            session.commit()

        return redirect(url_for("campaign.view", id=campaign.id))

    flash("Valid code")

    campaign = session.get(Campaign, inv.object_id)
    joinform = JoinCampaignForm(invite_code=code)

    return render_template(
        "campaign/joincampaign.html.jinja", campaign=campaign, joinform=joinform
    )


@bp.route("/<int:id>", methods=("GET", "POST"))
@login_required
def view(id: int):
    invites = None
    campaign: Campaign = session.get(Campaign, id)
    if not campaign:
        abort(404)

    # Set up forms
    inviteform = InvitePlayerForm(prefix="inviteform")
    createinviteform = CreateInviteForm(prefix="createinviteform")
    characterform = AddCharacterForm(prefix="characterform")
    npcform = AddNPCForm(prefix="npcform")

    messageform = MessagePlayerForm(
        players=[
            (campaign.user_id, "GM"),
        ]
        + [(p.id, p.user.username) for p in campaign.players],
        campaign_id=campaign.id,
        from_id=current_user.profile.id,
    )

    is_player = current_user.profile in campaign.players
    is_owner = current_user and current_user.profile.id == campaign.user_id

    logger.debug(f"Viewing campagin {campaign.title}")
    logger.debug(f"There are {campaign.players.count()} players")
    logger.debug(f"There are {len(campaign.character_associations)} characters")

    if not is_player and not is_owner:
        abort(404, "This is not the campaign your are looking for.")

    if is_owner:
        if createinviteform.submit.data and createinviteform.validate_on_submit():
            invite = Invite(campaign)
            invite.owner_id = campaign.user_id  # type: ignore
            session.add(invite)
            session.commit()

        if inviteform.submit.data and inviteform.validate_on_submit():
            player = User.query.filter_by(email=inviteform.email.data).first().profile
            campaign.players.append(player)
            session.commit()
            return redirect(url_for("campaign.view", id=id))

        invites = Invite.query_for(campaign)

        if npcform.submit.data and npcform.validate_on_submit():
            print("Adding NPC")
            character = npcform.character.data
            npc = NPC(character=character, campaign=campaign)
            session.add(npc)
            session.commit()

            return redirect(url_for("campaign.view", id=id))

    if characterform.submit.data and characterform.validate_on_submit():
        print("Adding character")
        character = characterform.character.data
        if (
            character not in campaign.characters
            and character
            and character.user_id == current_user.profile.id
        ):
            campaign_character = CampaignCharacter()
            campaign_character.character = character
            campaign.character_associations.append(campaign_character)
            session.commit()
        else:
            flash("Character is already added to campaign")

        return redirect(url_for("campaign.view", id=id))

    createinviteform.submit.label.text = "Create share link."

    handouts = campaign.handouts.filter_by(status=HandoutStatus.visible)
    messages = campaign.messages.filter(
        or_(
            Message.from_id == current_user.profile.id,
            Message.to_id == current_user.profile.id,
            Message.to_id.is_(None),
        )
    )

    added_npc_ids = [c.character_id for c in campaign.NPCs]

    npcform.character.query = (
        current_user.profile.characters.filter(Character.id.notin_(added_npc_ids))
        .order_by(desc(Character.folder_id.__eq__(campaign.folder_id)))
        .order_by("title")
    )

    added_character_ids = [c.character_id for c in campaign.character_associations]
    characterform.character.query = (
        current_user.profile.characters.filter(Character.id.notin_(added_character_ids))
        .order_by(desc(Character.folder_id.__eq__(campaign.folder_id)))
        .order_by("title")
    )

    return render_template(
        "campaign/campaign.html.jinja",
        campaign=campaign,
        handouts=handouts,
        invites=invites,
        inviteform=inviteform,
        createinviteform=createinviteform,
        characterform=characterform,
        messages=messages,
        npcform=npcform,
        editable=is_owner,
        messageform=messageform,
    )


@bp.route("/<int:id>/edit", methods=("GET", "POST"))
def edit(id: int):
    campaign = session.get(Campaign, id)
    assert campaign
    form = EditForm(obj=campaign, prefix="campaign_edit")
    folderform = ChooseFolderForm(prefix="choose_folder")
    deleteform = DeleteForm(obj=campaign, prefix="delete_campaign")

    if deleteform.submit.data and deleteform.validate_on_submit():
        if deleteform.confirm.data == "CONFIRM":
            print("DELETE CAMPAIGN!")
            invites = Invite.query_for(campaign)
            if invites:
                invites.delete()

            session.delete(campaign)
            session.commit()
            return redirect("/")
        else:
            return redirect(url_for("campaign.edit", id=campaign.id))

    if form.submit.data and form.validate_on_submit():
        form.populate_obj(campaign)
        session.add(campaign)
        session.commit()
        return redirect(url_for("campaign.view", id=campaign.id))

    if folderform.choose.data and folderform.validate_on_submit():
        print("Folder form submitted!")
        campaign.folder = folderform.folder_id.data
        session.commit()
        return redirect(url_for("campaign.view", id=campaign.id))

    folderform.folder_id.data = campaign.folder
    invites = Invite.query_for(campaign).count()
    return render_template(
        "campaign/edit.html.jinja",
        form=form,
        folderform=folderform,
        deleteform=deleteform,
        campaign=campaign,
        invites=invites,
    )


@bp.route("/<int:id>/export", methods=("GET",))
@login_required
def export(id: int):
    campaign: Campaign = session.get(Campaign, id)
    assert campaign
    return campaign.to_dict(_hide=[])


@bp.route("/create", methods=("GET", "POST"))
@login_required
def create():
    form = CreateForm()
    if form.validate_on_submit():
        c = Campaign(title=form.title.data, user_id=current_user.profile.id)
        session.add(c)
        session.commit()
        return redirect(url_for("campaign.view", id=c.id))
    return render_template("campaign/create.html.jinja", form=form)


@bp.route("/<int:id>/removecharacter/<int:characterid>", methods=("GET", "POST"))
@login_required
def remove_character(id: int, characterid: int):
    campaign = session.get(Campaign, id)
    assert campaign
    char = session.get(Character, characterid)
    assert char
    if (
        current_user.profile.id != campaign.user_id
        and char.user_id != current_user.profile.id
    ):
        abort(404)
    form = RemoveCharacterForm()

    if form.validate_on_submit():
        session.delete(session.get(CampaignCharacter, (char.id, campaign.id)))
        session.commit()
        return redirect(url_for("campaign.view", id=campaign.id))

    form.id.data = campaign.id
    form.character.data = char.id
    return render_template(
        "campaign/removecharacter.html.jinja",
        character=char,
        campaign=campaign,
        form=form,
    )


@bp.route("/<int:id>/association_settings/<int:characterid>", methods=("GET", "POST"))
@login_required
def association_settings(id: int, characterid: int):
    """Character-campaign association settings view."""
    association = session.get(CampaignCharacter, (characterid, id))
    assert association

    if current_user.profile.id != association.character.user_id:
        abort(403)

    form = CampaignAssociationForm(obj=association)

    if form.validate_on_submit():
        form.populate_obj(association)
        session.add(association)
        session.commit()
        return redirect(url_for("campaign.view", id=association.campaign_id))

    form.campaign_id.data = association.campaign_id
    form.character_id.data = association.character_id

    logger.debug(association)

    return render_template(
        "campaign/campaign_association.html.jinja",
        association=association,
        character=association.character,
        campaign=association.campaign,
        form=form,
    )

src/whathappened/web/campaign/__init__.py
from pelican.plugins.webassets.vendor.webassets.env import Environment


from . import routes  # noqa: F401,E402 isort:skip
from . import views  # noqa: F401, E402 isort:skip
from . import api  # noqa: F401, E402 isort:skip
from ...core.campaign.models import Campaign  # noqa: F401, E402 isort:skip


def register_assets(assets: Environment):
    assets.register(
        "scss_campaign",
        "scss/campaign/campaign.scss",
        filters="pyscss",
        output="css/campaign.css",
    )

    assets.register(
        "scss_handout",
        "scss/campaign/handout.scss",
        filters="pyscss",
        output="css/handout.css",
    )

src/whathappened/web/campaign/blueprints.py
"""Campaign blueprints."""

from flask import Blueprint

bp = Blueprint(
    "campaign", __name__, template_folder="templates", static_folder="static"
)
apibp = Blueprint("campaignapi", __name__)

src/whathappened/templates/campaign/campaign_association.html.jinja
{% extends 'base.html.jinja' %}

{% block header %}
  <h2>{% block title %}Update campaign association settings.{% endblock %}</h2>
{% endblock %}

{% block content %}
      <form action="" method="post">
    {{ form.hidden_tag() }}

    <p>
    {{ form.editable_by_gm.label }}
    {{ form.editable_by_gm }}<br>
    {% for error in form.editable_by_gm.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
    {{ form.share_with_players.label }}
    {{ form.share_with_players }}<br>
    {% for error in form.share_with_players.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}

    {{ form.group_sheet.label }}
    {{ form.group_sheet }}<br>
    {% for error in form.group_sheet.errors %}
    <span style="color: red;">[{{ error }}]</span>
    {% endfor %}
    </p>

      <p>{{ form.submit() }}</p>
  </form>
{% endblock %}

src/whathappened/templates/campaign/campaign_characters.html.jinja
{%- macro character_info(character_association) %}
                <div class="characterinfo splitcontainer">
                    <div style="display: flex; flex-direction: column; justify-content: space-between;">
                        <div class="personalia">
                        {{ character_association.character.name }} {%- if character_association.character.age %} ({{ character_association.character.age }}){%- endif %}<br />
                        {{ character_association.character.description }}<br />
                        {% if character_association.character.info %}<span>{{ character_association.character.info }}</span>{% endif %}
                        </div>
                        <div class="userinfo">
                        <em>Owner: {{ character_association.character.player.display_name or character_association.character.player.user.username }}</em><br />
                        {% if character_association.character.viewable_by(current_user.profile)%}
                        [<a href="{{url_for('character.view', character_id=character_association.character.id)}}" {%- if character_association.character.player.user == current_user %} class="strong"{%- endif %}>View</a>]{%endif %}
                        {%- if editable or character_association.character.player.user == current_user %}
                            [<a href="{{ url_for('campaign.remove_character', campaign_id=campaign.id, characterid=character_association.character.id) }}">Remove</a>]
                        {%- endif %}
                        {%- if character_association.character.player.user == current_user %}
                            [<a href="{{ url_for('campaign.association_settings', campaign_id=campaign.id, characterid=character_association.character.id)}}">Sharing</a>]
                        {%- endif %}
                        </div>
                    </div>
                    <div class="portrait">
                    {% if character_association.character.portrait %}<img src="data:image/jpg;base64, {{ character_association.character.portrait }}" />{% else %}<img src="{{ url_for('static', filename='images/placeholderportrait.png')}}" />{% endif %}
                    </div>
                </div>
{%- endmacro %}


<section class="characters box">
<h3>Characters</h3>
    <div>
    {% if campaign.character_associations %}
        {% for association in campaign.character_associations %}
            {{ character_info(association) }}          
        {% endfor %}
    {% else %}
        There are no characters.
    {% endif %}
    </div>

    <div>
        <input id="show_add_character" type="checkbox" autocomplete="off"><label for="show_add_character">Add character</label>
        <form action="" method="post" id="add_character_form">
            {{ characterform.hidden_tag() }}
            {{ characterform.character() }} {{ characterform.submit() }}
            {% for error in characterform.character.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </form>
    </div>
</section>

src/whathappened/templates/campaign/campaign_document.html.jinja
<div class="box campaign_document">
<h3>Document</h3>
<iframe src='{{ pad_data.endpoint }}/p/{{ pad_data.group_id }}$campaign_document_{{ campaign.id }}?showChat=false&showLineNumbers=false&userName={{ current_user.username }}' width="100%" height="600px"></iframe>
</div>

src/whathappened/templates/campaign/campaign_handouts.html.jinja
<section class="handouts box{%- if editable %} editable{%- endif %}" id="handout_section">
<h3>Handouts</h3>

{% if editable %}
<table class="table-header-rotated handoutshares">
<thead>
<tr>
    <th></th>
    {% for player in campaign.players %}
    <th class="rot90">
        <div>
            <span>
            {{ player.user.username }}
            </span>
        </div>
    </th>
    {% endfor %}
</tr>
</thead>
<tbody>
{% for handout in handouts %}
    <tr>      
        <th><a href="{{ url_for('campaign.handout_view', campaign_id=campaign.id, handout_id=handout.id) }}">{{ handout.title }}</a></th>
        {% for player in campaign.players %}
        <td>
            <input type="checkbox" autocomplete="off" {%- if player in handout.players %}checked{%- endif %} data-handout="{{ handout.id }}"  data-campaign="{{ campaign.id }}" data-player="{{ player.id }}"/>
        </td>
        {% endfor %}
    </tr>
{% endfor %}
</tbody>
</table>
    <a href="{{ url_for('campaign.handout_view', campaign_id=campaign.id) }}">Edit handouts</a>
{% else %}
    <ul class="player_handouts" data-campaign="{{ campaign.id}}">
{% for handout in handouts %}
    {%- if current_user.profile in handout.players %}<li><a href="{{ url_for('campaign.handout_view', campaign_id=campaign.id, handout_id=handout.id) }}">{{ handout.title }}</a></li>{%- endif %}
{% endfor %}
    </ul>

    [<a href="{{ url_for('campaign.handout_view', campaign_id=campaign.id) }}">Archive</a>]

{% endif %}
</section>

src/whathappened/templates/campaign/campaign_messages.html.jinja
<div class="box campaign_messages">
<h3>Messages</h3>
{% if messages %}
<table id="campaign_messages">
<tr>
    <th>Time</th>
    <th>From</th>
    <th>To</th>
    <th>Message</th>
</tr>
</table>
{% endif %}
<div class="message_form">
    <form action="{{ url_for('campaign.message_player', campaign_id=campaign.id) }}" method="post">
        {{ messageform.hidden_tag() }}
        {{ messageform.message(autocomplete="off") }}
        {% for error in messageform.message.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
        To: 
        {{ messageform.to_id() }}
        {{ messageform.submit() }}
    </form>
</div>
</div>

src/whathappened/templates/campaign/campaign_npcs.html.jinja
<section class="npcs box{%- if editable %} editable{%- endif %}" id="npc_section" data-campaign="{{ campaign.id }}">
    <h3>NPCs</h3>
    <div id="npc_list">
    {% if campaign.NPCs %}
        {% for npc in campaign.NPCs %}
            {%- if editable or npc.visible %}{{ npc_info(npc) }}{%- endif %}
        {% endfor %}
    {% else %}
        There are no NPCs.
    {% endif %}
    </div>
    {% if editable %}
    <div>
        <input id="show_add_npc" type="checkbox" autocomplete="off"><label for="show_add_npc">Add NPC</label>
        <form action="" method="post" id="add_npc_form">
            {{ npcform.hidden_tag() }}
            {{ npcform.character() }} {{ npcform.submit() }}
            {% for error in npcform.character.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </form>
    </div>
    {% endif %}
</section>

src/whathappened/templates/campaign/create.html.jinja
{% extends 'base.html.jinja' %}

{% block header %}
  <h2>{% block title %}New Campaign{% endblock %}</h2>
{% endblock %}

{% block content %}
  <form action="" method="post">
    {{ form.hidden_tag() }}
        <p>
          {{ form.title.label }}<br>
          {{ form.title(size=32) }}<br>
          {% for error in form.title.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>{{ form.submit() }}</p>
  </form>
{% endblock %}

src/whathappened/templates/campaign/delete_handout.html.jinja
{% extends 'base.html.jinja' %}

{% block head %}
    {{ super() }}

{% endblock %}

{% block header %}
    <h2>{% block title %}Delete handout "{{ handout.title }}" ? {% endblock %}</h2>
{% endblock %}

{% block content %}
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        {{ form.submit() }}
    </form>
{% endblock %}

src/whathappened/templates/campaign/edit.html.jinja
{% extends 'base.html.jinja' %}

{% block header %}
  <h2>{% block title %}Edit campaign{% endblock %}</h2>
{% endblock %}

{% block content %}
  <form action="" method="post">
    {{ form.hidden_tag() }}
        <p>
          {{ form.title.label }}<br>
          {{ form.title(size=32) }}<br>
          {% for error in form.title.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
        <p>
          {{ form.description.label }}<br>
          {{ form.description }}<br>
          {% for error in form.description.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
        <p>
          {{ form.characters_enabled.label }}
          {{ form.characters_enabled }}<br>
          {% for error in form.characters_enabled.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
          {{ form.npcs_enabled.label }}
          {{ form.npcs_enabled }}<br>
          {% for error in form.npcs_enabled.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
          {{ form.handouts_enabled.label }}
          {{ form.handouts_enabled }}<br>
          {% for error in form.handouts_enabled.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
          {{ form.messages_enabled.label }}
          {{ form.messages_enabled }}<br>
          {% for error in form.messages_enabled.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
          {{ form.document_enabled.label }}
          {{ form.document_enabled }}<br>
          {% for error in form.document_enabled.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>{{ form.submit() }}</p>
  </form>
  <form action="" method="post">
    {{ folderform.hidden_tag() }}
        <p>
        Put in folder: 
            {{ folderform.folder_id }}
            {% for error in folderform.folder_id.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}

            {{ folderform.choose()}}
        </p>

  </form>
  <section>
  <h3>Numbers</h3>
  <ul>
  <li>Players: {{ campaign.players.count() }}</li>
  <li>Characters: {{ campaign.characters.count() }}</li>
  <li>NPCs: {{ campaign.NPCs.count() }} </li>
  <li>Handouts: {{ campaign.handouts.count() }}</li>
  <li>Handout groups: {{ campaign.handout_groups.count() }}</li>
  <li>Messages: {{ campaign.messages.count() }}</li>
  <li>Invites: {{ invites }}</li>
  
  </ul>
  </section>
  <section>
  <h3>Danger zone</h3>
  <form action="" method="post">
  {{ deleteform.hidden_tag() }}
  <p>
    {{ deleteform.id }}
    To delete the campaign, write CONFIRM in the input field, then press Delete.
    It will immediatly delete the campaign, all associated handouts, messages and invites, and it can not be undone!
    {{ deleteform.confirm }}
    {{ deleteform.submit }}
  </p>
  </form>
  </section>
{% endblock %}